import type { Metadata } from "next";
import "./globals.css";

import { Roboto } from "next/font/google";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Firoz Mridha",
  description: "Generated by Tech Sand",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.className}>
      <body className="bg-primary text-white">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
